GNCommon::NNotification::TcAlert
const Tu32 GNCommon::NNotification::TcAlert::XuiSizeOfIdentifier
Size of Identifier
const Tu32 GNCommon::NNotification::TcAlert::XuiSizeOfStatus
Size of Status
TcIdentifier GNCommon::NNotification::TcAlert::voID
Encoded Identifier
Referenced by operator=, MSetIdentifier, MGetIdentifier.
TcStatus GNCommon::NNotification::TcAlert::voStatus
Encoded Status
Referenced by operator=, MSetStatus, MGetStatus.
Tu64 GNCommon::NNotification::TcAlert::vulTimestamp
64-bit Timestamp of Occurrence
Referenced by TcAlert, operator=, MSetTimestamp, MGetTimestamp.
Tu64 GNCommon::NNotification::TcAlert::vulData
64-bit Additional Data
Referenced by TcAlert, operator=, MSetData, MGetData.
TcAlert::TcAlert(void)
Default Constructor
References vulTimestamp, vulData.
TcAlert::~TcAlert(void)
Default Destructor
TcAlert::TcAlert(const TcAlert &aorAlert)
Copy Constructor aorAlert Alert Constant Reference to copy
TcAlert & TcAlert::operator=(const TcAlert &aorAlert)
operator= Override aorAlert Alert Constant Reference to copy *this GTcAlert Reference
References MSetIdentifier, voID, MSetStatus, voStatus, MSetTimestamp, vulTimestamp, MSetData, vulData.
void TcAlert::MSetIdentifier(const TcIdentifier &aorID)
MSetIdentifier aorID Identifier Structure Constant Reference
References voID.
Referenced by operator=.
void TcAlert::MSetStatus(const TcStatus &aorStatus)
MSetStatus aorStatus Status Structure Constant Reference
References voStatus.
Referenced by operator=.
void TcAlert::MSetTimestamp(const Tu64 aulTimestamp)
MSetTimeStamp aulTimestamp constant 64-bit Integer Timestamp
References vulTimestamp.
Referenced by operator=.
void TcAlert::MSetData(const Tu64 aulData)
MSetData aulData constant 64-bit Integer Data
References vulData.
Referenced by operator=.
TcIdentifier TcAlert::MGetIdentifier(void) const
MGetIdentifier this->voID constant TsIdentifier
References voID.
TcStatus TcAlert::MGetStatus(void) const
MGetStatus this->voStatus constant TsStatus
References voStatus.
Tu64 TcAlert::MGetTimestamp(void) const
MGetTimestamp this->vulTimestamp constant 64-bit Integer Timestamp
References vulTimestamp.
Tu64 TcAlert::MGetData(void) const
MGetTrigger this->vulData constant 64-bit Integer Data
References vulData.